# Generated by Django 6.0.3 on 2026-03-06 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('college_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('fingerprint_template', models.BinaryField(max_length=4096)),
                ('fingerprint_hash', models.CharField(max_length=64)),
                ('consent_signed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalForm',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('form_pdf', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='medical_forms', to='fingerprint.student')),
            ],
            options={
                'db_table': 'medical_forms',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
