# Generated by Django 5.2.4 on 2026-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fingerprint_image',
            field=models.BinaryField(blank=True, max_length=262144, null=True),
        ),
    ]
