# Generated by Django 5.2.4 on 2026-05-12 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0002_student_fingerprint_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=150)),
                ('user_role', models.CharField(blank=True, max_length=50)),
                ('action', models.CharField(choices=[('APPROVE', 'Registration Approved'), ('REJECT', 'Registration Rejected'), ('REUPLOAD', 'Re-upload Requested'), ('BULK_APPROVE', 'Bulk Approve'), ('OVERRIDE', 'Entry Override'), ('FALLBACK', 'Fallback Auth Used'), ('ALERT', 'Security Alert'), ('SEAT_MAP', 'Seat Map Generated'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExamCenter',
            fields=[
                ('center_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exam_centers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='special_needs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='special_needs_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REUPLOAD_REQUESTED', 'Re-upload Requested')], default='SUBMITTED', max_length=30),
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rows', models.PositiveIntegerField(default=10)),
                ('columns', models.PositiveIntegerField(default=10)),
                ('total_capacity', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(db_column='center_id', on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='fingerprint.examcenter')),
            ],
            options={
                'db_table': 'halls',
                'ordering': ['center', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=180)),
                ('cutoff_date', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_students', models.ManyToManyField(blank=True, related_name='exams', to='fingerprint.student')),
                ('center', models.ForeignKey(db_column='center_id', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='fingerprint.examcenter')),
                ('halls', models.ManyToManyField(blank=True, related_name='exams', to='fingerprint.hall')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='fingerprint.subject')),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_state', models.CharField(choices=[('GRANTED', 'Granted'), ('WRONG_HALL', 'Wrong Hall'), ('ALREADY_ENTERED', 'Already Entered'), ('MATCH_FAILED', 'Match Failed'), ('FALLBACK_GRANTED', 'Fallback Granted'), ('DENIED', 'Denied')], default='GRANTED', max_length=30)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(blank=True, default='fingerprint', max_length=50)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='fingerprint.student')),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='fingerprint.exam')),
                ('hall', models.ForeignKey(blank=True, db_column='hall_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='fingerprint.hall')),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationDocument',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('GOVT_ID', 'Government ID'), ('PASSPORT_PHOTO', 'Passport Photo'), ('FINGERPRINT', 'Fingerprint Image'), ('OTHER', 'Other')], default='GOVT_ID', max_length=30)),
                ('file_data', models.BinaryField()),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30)),
                ('verification_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fingerprint.student')),
            ],
            options={
                'db_table': 'registration_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='fingerprint.subject'),
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.PositiveIntegerField(blank=True, null=True)),
                ('col', models.PositiveIntegerField(blank=True, null=True)),
                ('seat_label', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='fingerprint.exam')),
                ('hall', models.ForeignKey(blank=True, db_column='hall_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='fingerprint.hall')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='fingerprint.student')),
            ],
            options={
                'db_table': 'seat_assignments',
                'ordering': ['exam', 'hall', 'row', 'col'],
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
