# Generated by Django 5.2.4 on 2026-05-21 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0003_initial_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('started_by', models.CharField(max_length=150)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='fingerprint.exam')),
            ],
            options={
                'db_table': 'exam_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
